Bumped dependencies due to modernization and vulnerabilities.
utily/cloudly-storage pull request #162
Opened 2024-02-21 10:53 UTC by AntonCroner

2024-02-22 10:27 UTC, marcushanses requested changes

2024-02-22 10:27 UTC, marcushanses commented on test-worker/Context/Do/alarm/set.ts
> +//import { isoly } from "isoly"
Remove

2024-02-22 10:45 UTC, AntonCroner commented on test-worker/Context/Do/alarm/set.ts
> +//import { isoly } from "isoly"
\+

2024-02-28 08:44 UTC, marcushanses approved these changes

2024-02-28 08:49 UTC, merged