Update README.md with description of the databse.
utily/cloudly-storage pull request #22
Opened 2022-08-09 12:50 UTC by marcushanses

2022-08-09 15:35 UTC, nilssonemma requested changes

2022-08-09 15:35 UTC, nilssonemma commented on README.md
> +The technology used in this database are Durable Objects and Key Value stores, there exists a low level abstraction aroung these technologies in the DurableObject and KeyValueStore folders respective
```suggestion
The technology used in this database are Durable Objects and Key Value stores, there exists a low level abstraction around these technologies in the DurableObject and KeyValueStore folders respectively.
```

2022-08-09 15:35 UTC, nilssonemma requested changes

2022-08-09 15:35 UTC, nilssonemma commented on README.md
> +
```suggestion
- The Collection utilizes a Durable Object abstraction called Buffer and an Archive for long term storage. The Buffer ensures consistency while writing and will write stale documents to the Archive. The buffer will contain several durable objects to increase the number of simultaneous read and writes, these durable objects will use a key-shard, the id of the document will generate a specific shard.

```

2022-08-10 15:16 UTC, Magnus93 approved these changes

2022-08-11 07:37 UTC, nilssonemma approved these changes

2022-08-11 07:38 UTC, merged