Archive buffer tests
utily/cloudly-storage pull request #42
Opened 2022-09-06 08:44 UTC by Hlebanja

2022-09-12 07:24 UTC, marcushanses requested changes

2022-09-12 07:24 UTC, marcushanses commented on Database/Document.spec.ts
> +		// console.log(appended && appended.county)
Remove console.logs :)

2022-09-12 07:24 UTC, marcushanses commented on Database/index.spec.ts
> +type Layout = { archive: { items: Partial<Item> } }
Instead of doing Partial I  would recommend making the properties you want to be optional optional.

2022-09-19 14:35 UTC, Magnus93 submitted a review, later dismissed

2022-09-19 15:01 UTC, marcushanses approved these changes

2022-09-19 15:01 UTC, merged