Created buffer cursor.
utily/cloudly-storage pull request #64
Opened 2022-10-12 15:52 UTC by Hlebanja

General improvements to listing.
Created tests in test-worker for listing collection.

2022-10-13 07:55 UTC, nilssonemma requested changes

2022-10-13 07:55 UTC, nilssonemma commented on Database/Archive.ts
> +				limit: limit,
```suggestion
				limit,
```

2022-10-13 07:55 UTC, nilssonemma commented on Database/Configuration/Buffer.spec.ts
> +	}
```suggestion
	for (let seed = 0; seed < mask + 1; seed++)
		result.push(cryptly.Identifier.fromBinary(new Uint8Array([seed ?? 0])) + "AA")
```

2022-10-13 07:55 UTC, nilssonemma commented on Database/Cursor/Buffer/index.ts
> +		return result
```suggestion
		const base = Base.from(selection)
		return selection?.cursor ? (base?.shard ? base : undefined) : base
```

2022-10-13 07:55 UTC, nilssonemma commented on test-worker/Context/TestSetup.ts
> +		}
```suggestion
		for (let seed = 0; seed < ids; seed++)
			result.push(cryptly.Identifier.fromBinary(new Uint8Array([seed ?? 0])) + suffix ?? "AA")
```

2022-10-13 08:10 UTC, marcushanses requested changes

2022-10-13 08:10 UTC, marcushanses commented on test-worker/db/collection/user/create.spec.ts
> +]
Remove this file.

2022-10-13 08:27 UTC, Hlebanja commented on test-worker/db/collection/user/create.spec.ts
> +]
Ops. Nice catch.

2022-10-13 08:37 UTC, marcushanses approved these changes

2022-10-25 13:39 UTC, nilssonemma approved these changes

2022-10-28 08:33 UTC, merged